services:
    flowcode.sender.senderEmailLocal:
        class:        Flowcode\NotificationBundle\Senders\EmailLocalSender
        calls:
            - [setContainer, ["@service_container"]]
    flowcode.sender.senderEmailMandrill:
        class:        Flowcode\NotificationBundle\Senders\EmailMandrillSender
        calls:
            - [setContainer, ["@service_container"]]

    flowcode.notification.email:
        class: Flowcode\NotificationBundle\Service\NotificationEmailService
        calls:
            - [setSender, ["@flowcode.sender.senderEmailMandrill"]]
            - [setContainer, ["@service_container"]]
